# Generated by Django 5.1.2 on 2024-11-09 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaizen_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kaizensheet',
            name='after_improvement_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='kaizensheet',
            name='before_improvement_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
