# Generated by Django 5.1.2 on 2024-11-09 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaizen_app', '0003_remove_profile_user_type_profile_is_coordinator_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_coordinator',
        ),
        migrations.AddField(
            model_name='profile',
            name='user_type',
            field=models.CharField(choices=[('employee', 'Employee'), ('coordinator', 'Coordinator'), ('admin', 'Admin')], default='employee', max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
