# Generated by Django 5.1.2 on 2024-11-15 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaizen_app', '0005_rename_admin_to_hod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_type',
            field=models.CharField(choices=[('employee', 'Employee'), ('coordinator', 'Coordinator'), ('hod', 'Hod')], default='employee', max_length=20),
        ),
    ]
