# Generated by Django 5.1.2 on 2024-11-15 05:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaizen_app', '0006_alter_profile_user_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='kaizensheet',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('hod_approved', 'HOD Approved'), ('coordinator_approved', 'Fully Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='kaizensheet',
            name='coordinator_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='kaizensheet',
            name='coordinator_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kaizensheet',
            name='coordinator_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coordinator_approved_sheets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='kaizensheet',
            name='hod_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='kaizensheet',
            name='hod_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kaizensheet',
            name='hod_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hod_approved_sheets', to=settings.AUTH_USER_MODEL),
        ),
    ]
