# Generated by Django 5.1.2 on 2024-11-21 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaizen_app', '0007_kaizensheet_approval_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kaizensheet',
            name='handwritten_sheet',
            field=models.ImageField(blank=True, null=True, upload_to='kaizen/handwritten/', verbose_name='Handwritten Kaizen Sheet'),
        ),
        migrations.AddField(
            model_name='kaizensheet',
            name='is_handwritten',
            field=models.BooleanField(default=False),
        ),
    ]
