# Generated by Django 5.1.2 on 2024-11-22 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaizen_app', '0008_kaizensheet_handwritten_sheet_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kaizensheet',
            name='estimated_savings',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='kaizensheet',
            name='project_leader',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='kaizensheet',
            name='realized_savings',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='kaizensheet',
            name='savings_start_month',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kaizensheet',
            name='supported_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='kaizensheet',
            name='team_member1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='kaizensheet',
            name='team_member1_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='kaizensheet',
            name='team_member2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='kaizensheet',
            name='team_member2_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
