# Generated by Django 5.1.2 on 2024-11-22 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaizen_app', '0010_remove_kaizensheet_estimated_savings_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kaizensheet',
            name='estimated_savings',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
