# Generated by Django 5.1.2 on 2024-11-22 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaizen_app', '0011_kaizensheet_estimated_savings'),
    ]

    operations = [
        migrations.AddField(
            model_name='kaizensheet',
            name='cost_calculation',
            field=models.FileField(blank=True, null=True, upload_to='kaizen/cost_calculations/', verbose_name='Cost Calculation File'),
        ),
    ]
