# Generated by Django 5.1.2 on 2024-11-23 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaizen_app', '0012_kaizensheet_cost_calculation'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='employee_id',
            field=models.CharField(blank=True, help_text='Unique employee identification number', max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='department',
            field=models.CharField(blank=True, choices=[('dept1', 'Department 1'), ('dept2', 'Department 2'), ('dept3', 'Department 3'), ('dept4', 'Department 4'), ('dept5', 'Department 5')], max_length=100, null=True),
        ),
    ]
