# Generated by Django 5.1.2 on 2024-11-29 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaizen_app', '0013_profile_employee_id_alter_profile_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_type',
            field=models.CharField(choices=[('employee', 'Employee'), ('coordinator', 'Coordinator'), ('hod', 'Hod'), ('finance', 'Finance and Accounts')], default='employee', max_length=20),
        ),
    ]
