# Generated by Django 5.1.2 on 2024-11-29 06:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaizen_app', '0014_alter_profile_user_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='kaizensheet',
            name='finance_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='kaizensheet',
            name='finance_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kaizensheet',
            name='finance_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finance_approved_sheets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='kaizensheet',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('hod_approved', 'HOD Approved'), ('finance_pending', 'Finance Review Pending'), ('finance_approved', 'Finance Approved'), ('coordinator_approved', 'Fully Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
