# Generated by Django 5.1.2 on 2024-11-29 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaizen_app', '0016_alter_kaizensheet_approval_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='kaizensheet',
            name='horizontal_departments',
            field=models.ManyToManyField(blank=True, limit_choices_to={'user_type': 'hod'}, related_name='horizontally_deployed_sheets', to='kaizen_app.profile'),
        ),
    ]
