# Generated by Django 5.1.2 on 2024-11-30 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaizen_app', '0017_kaizensheet_horizontal_departments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kaizensheet',
            name='horizontal_departments',
            field=models.ManyToManyField(blank=True, limit_choices_to={'user_type': 'hod'}, related_name='horizontal_kaizens', to='kaizen_app.profile'),
        ),
    ]
