# Generated by Django 5.1.2 on 2024-11-30 05:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaizen_app', '0019_remove_kaizensheet_horizontal_departments_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kaizensheet',
            name='horizontal_departments',
        ),
        migrations.CreateModel(
            name='HorizontalDeployment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=100)),
                ('deployed_at', models.DateTimeField(auto_now_add=True)),
                ('kaizen_sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deployments', to='kaizen_app.kaizensheet')),
            ],
            options={
                'unique_together': {('kaizen_sheet', 'department')},
            },
        ),
    ]
