# Generated by Django 5.1.2 on 2025-01-30 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kaizen_app', '0025_alter_profile_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kaizensheet',
            name='benefits',
        ),
    ]
