# Generated by Django 5.1.2 on 2025-02-05 12:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaizen_app', '0027_alter_profile_employee_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_department_change',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
