# Generated by Django 5.1.2 on 2025-02-06 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaizen_app', '0031_alter_profile_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='kaizensheet',
            name='area_grouping',
            field=models.CharField(blank=True, choices=[('ASSEMBLY MECH', 'ASSEMBLY MECH'), ('CSG, QA, METHODS, MAINTENACE & STORES', 'CSG, QA, METHODS, MAINTENACE & STORES'), ('ELECTRICAL', 'ELECTRICAL'), ('M/C SHOP, PAINTSHOP & DISPATCH', 'M/C SHOP, PAINTSHOP & DISPATCH'), ('OFFICE', 'OFFICE'), ('SCM', 'SCM'), ('TECH SUPPORT GROUP', 'TECH SUPPORT GROUP')], max_length=100, null=True),
        ),
    ]
