# Generated by Django 5.1.2 on 2025-02-06 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaizen_app', '0032_add_area_grouping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kaizensheet',
            name='area_implemented',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
