# Generated by Django 5.1.2 on 2025-02-08 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaizen_app', '0035_remove_profile_unique_user_type_per_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kaizensheet',
            name='employee_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='kaizensheet',
            name='employee_info',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
