# Generated by Django 5.1.2 on 2025-02-08 06:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaizen_app', '0036_kaizensheet_employee_active_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordResetRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('department', models.CharField(choices=[('ASSLY MECH- VMC GROUP - RAPC', 'ASSLY MECH- VMC GROUP - RAPC'), ('ASSLY MECH- BB -SA- HS & IT', 'ASSLY MECH- BB -SA- HS & IT'), ('ASSLY MECH- HMC GROUP', 'ASSLY MECH- HMC GROUP'), ('ASSLY MECH- L VMC GROUP', 'ASSLY MECH- L VMC GROUP'), ('ASSLY MECH- LINE ASSLY 1 & 2', 'ASSLY MECH- LINE ASSLY 1 & 2'), ('ASSLY MECH- LINE ASSLY 3 & 4', 'ASSLY MECH- LINE ASSLY 3 & 4'), ('ASSLY MECH- VMC GROUP - 2', 'ASSLY MECH- VMC GROUP - 2'), ('ASSLY MECH- VMC GROUP - 1', 'ASSLY MECH- VMC GROUP - 1'), ('ASSLY MECH- VMC GROUP - LAPC', 'ASSLY MECH- VMC GROUP - LAPC'), ('BASE BUILD- SA- SPINDLE', 'BASE BUILD- SA- SPINDLE'), ('CSG', 'CSG'), ('EEP', 'EEP'), ('ELCT- DESIGN', 'ELCT- DESIGN'), ('ELCT- FINAL ASSLY (HMC)', 'ELCT- FINAL ASSLY (HMC)'), ('ELCT- FINAL ASSLY (LVMC)', 'ELCT- FINAL ASSLY (LVMC)'), ('ELCT- FINAL ASSLY (EXPORT)', 'ELCT- FINAL ASSLY (EXPORT)'), ('ELCT- FINAL ASSLY (SKI)', 'ELCT- FINAL ASSLY (SKI)'), ('ELCT- LINE ASSLY (SKI)', 'ELCT- LINE ASSLY (SKI)'), ('ELCT- METHODS', 'ELCT- METHODS'), ('ELCT- PLANNING', 'ELCT- PLANNING'), ('ELCT- PROCUREMENT', 'ELCT- PROCUREMENT'), ('ELCT- SUB ASSLY (SKI)', 'ELCT- SUB ASSLY (SKI)'), ('EXPORT ASSEMBLY', 'EXPORT ASSEMBLY'), ('FINAL ASSLY- SA', 'FINAL ASSLY- SA'), ('FINANCE & ACCOUNTS', 'FINANCE & ACCOUNTS'), ('FIXTURE DESIGN', 'FIXTURE DESIGN'), ('HRD', 'HRD'), ('ISG', 'ISG'), ('MACHINE SHOP', 'MACHINE SHOP'), ('MAINTENANCE', 'MAINTENANCE'), ('METHODS ENGG', 'METHODS ENGG'), ('PAINT SHOP & PACKING- DISPATCH', 'PAINT SHOP & PACKING- DISPATCH'), ('PROD PLANNING & CONTROL', 'PROD PLANNING & CONTROL'), ('PRODUCT DESIGN- HMC GROUP', 'PRODUCT DESIGN- HMC GROUP'), ('PRODUCT DESIGN- VMC GROUP', 'PRODUCT DESIGN- VMC GROUP'), ('PROJECTS', 'PROJECTS'), ('QUALITY- CIP, CMM & CALIBRATION', 'QUALITY- CIP, CMM & CALIBRATION'), ('QUALITY- FNL INSPTN, LASER & BALL BAR', 'QUALITY- FNL INSPTN, LASER & BALL BAR'), ('QUALITY- INWARD INSPECTION', 'QUALITY- INWARD INSPECTION'), ('R & D', 'R & D'), ('SCM- A CLASS', 'SCM- A CLASS'), ('SCM- B & C CLASS', 'SCM- B & C CLASS'), ('SCM- BROUGHTOUT', 'SCM- BROUGHTOUT'), ('SCM- COSTING & INVENTORY CONTROL', 'SCM- COSTING & INVENTORY CONTROL'), ('SCM- HMC EXCLUSIVE', 'SCM- HMC EXCLUSIVE'), ('SCM- PE (CASTING/ FOUNDRY)', 'SCM- PE (CASTING/ FOUNDRY)'), ('SCM- PROCESS ENGG', 'SCM- PROCESS ENGG'), ('SCM- SHEET METAL', 'SCM- SHEET METAL'), ('SCM- FIXTURES', 'SCM- FIXTURES'), ('STORES', 'STORES'), ('SUB ASSEMBLY- FIXTURE', 'SUB ASSEMBLY- FIXTURE'), ('TRYOUTS', 'TRYOUTS'), ('TSG- APPLICATION ENGINEERING', 'TSG- APPLICATION ENGINEERING'), ('TSG- AUTOMATION', 'TSG- AUTOMATION'), ('TSG- DIE & MOULD', 'TSG- DIE & MOULD'), ('TSG- EXPORT', 'TSG- EXPORT'), ('TSG- MARKETING & BRANDING', 'TSG- MARKETING & BRANDING'), ('TSG- SALES & EXECUTION', 'TSG- SALES & EXECUTION'), ('SUB_ASSLY - RAPC,LAPC, SLIDE ASSEMBLY', 'SUB_ASSLY - RAPC,LAPC, SLIDE ASSEMBLY')], max_length=100)),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('resolved_date', models.DateTimeField(blank=True, null=True)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_password_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-request_date'],
            },
        ),
    ]
