# Generated by Django 5.1.2 on 2025-02-08 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaizen_app', '0037_passwordresetrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_type',
            field=models.CharField(choices=[('employee', 'Employee'), ('coordinator', 'Coordinator'), ('hod', 'Hod'), ('hod_coordinator', 'HOD Coordinator'), ('finance', 'Finance and Accounts'), ('admin', 'Admin')], default='employee', max_length=20),
        ),
    ]
